version: "3"
services:
  app:
    container_name: api.php
    build: .
    volumes:
      - ./app:/app
    restart: always
    links:
      - mysql
  web:
    container_name: web.nginx
    image: nginx:latest
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./app:/app
      - ./site.conf:/etc/nginx/conf.d/site.conf
    links:
      - app
  mysql:
    image: mysql:latest
    container_name: mysql
    ports:
      - "3306:3306"
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: teste
  phpmyadmin:
    image: phpmyadmin:latest
    container_name: phpmyadmin
    restart: always
    ports:
      - "8080:80"
    links:
      - mysql
    environment:
      - PMA_ARBITRARY=1